
name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Install cloc
      run: sudo apt-get install -y cloc
    - name: Count lines of code
      run: cloc .
    - name: Build with Maven
      run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: 25db9047-7c6d-461a-b63d-181a4749d6f2
        slug: eozoo/http-client
        file: ${{ github.workspace }}/target/site/jacoco/jacoco.xml

